import type { ArchiveEntry, DrinkEntry } from './types'

/**
 * Seed content for the ARKIB archive system. These are illustrative
 * placeholders written in the ARKIB voice — real drinks, people, and
 * copy should replace them before launch. The data shape is the durable
 * part: add/remove/edit entries here and every page that reads from it
 * (home, /drinks, /people, /archive) updates without touching layout.
 */

export const DRINKS: DrinkEntry[] = [
  {
    id: 'old-fashioned',
    number: 14,
    category: 'drink',
    title: 'Old Fashioned',
    kicker: 'The standard',
    description: 'A study in warmth, bitterness and time.',
    idea: 'Nothing added that isn’t earning its place. The oldest drink in the room, made slower than it needs to be.',
    technique: 'Stirred, single block, expressed peel.',
    ingredients: ['Bourbon', 'Demerara', 'Orange oil', 'Aromatic bitters'],
    price: 'RM 42',
    image: { alt: 'Old Fashioned in low tungsten light', tone: 'tobacco', plate: 'PLATE 014' },
    metadata: [{ label: 'ABV', value: '32%' }, { label: 'Glass', value: 'Rocks' }],
    tags: ['spirit-forward', 'classic'],
    featured: true,
    status: 'in-rotation',
  },
  {
    id: 'smoke-room',
    number: 21,
    category: 'drink',
    title: 'Smoke Room',
    kicker: 'House original',
    description: 'Clove, tobacco leaf, and a rum that remembers where it was aged.',
    idea: 'Built around scent before taste — the glass is sealed and smoked at the table.',
    technique: 'Smoked, double-strained, no ice contact after smoking.',
    ingredients: ['Aged rum', 'Clove tincture', 'Tobacco leaf tea', 'Bitter orange'],
    price: 'RM 48',
    image: { alt: 'Smoke Room being smoked tableside', tone: 'ink', plate: 'PLATE 021' },
    metadata: [{ label: 'ABV', value: '29%' }, { label: 'Glass', value: 'Smoke dome' }],
    tags: ['smoked', 'house original'],
    featured: true,
    status: 'in-rotation',
  },
  {
    id: 'paper-trail',
    number: 7,
    category: 'drink',
    title: 'Paper Trail',
    kicker: 'House original',
    description: 'Gin, dried citrus, and a document that was never meant to survive.',
    technique: 'Fat-washed, clarified, still.',
    ingredients: ['Gin', 'Clarified lime', 'Dried mandarin peel', 'Chamomile'],
    price: 'RM 40',
    image: { alt: 'Paper Trail cocktail, clarified and pale', tone: 'paper', plate: 'PLATE 007' },
    metadata: [{ label: 'ABV', value: '18%' }, { label: 'Glass', value: 'Coupe' }],
    tags: ['clarified', 'light'],
    status: 'in-rotation',
  },
  {
    id: 'low-tide',
    number: 33,
    category: 'drink',
    title: 'Low Tide',
    kicker: 'Seasonal',
    description: 'Brine, samphire, and the strait at the hour the boats come in.',
    technique: 'Shaken hard, saline rinse, served over crushed ice.',
    ingredients: ['Blanco tequila', 'Samphire cordial', 'Yuzu', 'Sea salt tincture'],
    price: 'RM 46',
    image: { alt: 'Low Tide over crushed ice', tone: 'smoke', plate: 'PLATE 033' },
    metadata: [{ label: 'ABV', value: '15%' }, { label: 'Glass', value: 'Highball' }],
    tags: ['seasonal', 'savoury'],
    status: 'seasonal',
  },
  {
    id: 'first-press',
    number: 2,
    category: 'drink',
    title: 'First Press',
    kicker: 'Zero-proof',
    description: 'Cold-pressed and cordial-led. Built with the same care as everything beside it.',
    technique: 'Pressed daily, batch cordial, shaken.',
    ingredients: ['Cold-pressed pineapple', 'House verjus', 'Lemongrass cordial', 'Soda'],
    price: 'RM 28',
    image: { alt: 'First Press, non-alcoholic cocktail', tone: 'tobacco', plate: 'PLATE 002' },
    metadata: [{ label: 'ABV', value: '0%' }, { label: 'Glass', value: 'Rocks' }],
    tags: ['zero-proof'],
    status: 'in-rotation',
  },
  {
    id: 'night-shift',
    number: 45,
    category: 'drink',
    title: 'Night Shift',
    kicker: 'Late list',
    description: 'For the hour when the room gets quieter and the drinks get darker.',
    technique: 'Stirred, cold-drip coffee reduction, orange oil.',
    ingredients: ['Amaro', 'Cold-drip coffee', 'Aged rum', 'Orange oil'],
    price: 'RM 44',
    image: { alt: 'Night Shift, dark and stirred', tone: 'ink', plate: 'PLATE 045' },
    metadata: [{ label: 'ABV', value: '24%' }, { label: 'Glass', value: 'Rocks' }],
    tags: ['late list', 'bitter'],
    status: 'in-rotation',
  },
]

export const ARCHIVE: ArchiveEntry[] = [
  ...DRINKS,
  {
    id: 'the-tape-that-never-stops',
    number: 19,
    category: 'sound',
    title: 'The Tape That Never Stops',
    description: 'A rotating tape and vinyl selection, chosen nightly, never repeated the same way twice.',
    image: { alt: 'Tape deck and vinyl at the bar', tone: 'smoke', plate: 'PLATE 019' },
    tags: ['music', 'resident'],
    status: 'ongoing',
  },
  {
    id: 'vetiver-and-wet-stone',
    number: 26,
    category: 'scent',
    title: 'Vetiver and Wet Stone',
    description: 'The room’s signature scent — diffused low, meant to be felt before it is noticed.',
    image: { alt: 'Diffuser detail, low light', tone: 'ink', plate: 'PLATE 026' },
    tags: ['scent design'],
    status: 'ongoing',
  },
  {
    id: '2700k',
    number: 11,
    category: 'light',
    title: '2700K',
    description: 'Every fixture in the room was chosen for one temperature. Warm enough to disappear.',
    image: { alt: 'Tungsten light across brass and wood', tone: 'tobacco', plate: 'PLATE 011' },
    tags: ['lighting design'],
    status: 'ongoing',
  },
  {
    id: 'the-back-room',
    number: 4,
    category: 'space',
    title: 'The Back Room',
    description: 'Six seats, one door, no sightline to the street. The room within the room.',
    image: { alt: 'The back room interior', tone: 'ink', plate: 'PLATE 004' },
    tags: ['interior'],
    status: 'ongoing',
  },
  {
    id: 'head-bartender',
    number: 38,
    category: 'person',
    title: 'Behind the Bar, Most Nights',
    description: 'Ten years in rooms like this one, most of them in Melaka. Prefers ice over garnish.',
    image: { alt: 'Bartender working service', tone: 'smoke', plate: 'PLATE 038' },
    tags: ['bartender'],
    status: 'ongoing',
  },
  {
    id: 'guest-shift-kl',
    number: 41,
    category: 'person',
    title: 'Guest Shift, Kuala Lumpur',
    description: 'One night a season, the bar belongs to someone else. This one came from KL with a suitcase of tinctures.',
    date: '2026',
    image: { alt: 'Guest bartender during a guest shift', tone: 'tobacco', plate: 'PLATE 041' },
    tags: ['guest shift'],
    status: 'one-night',
  },
  {
    id: 'the-door',
    number: 29,
    category: 'person',
    title: 'The Door',
    description: 'The first and last person you meet. Remembers regulars by their order, not their name.',
    image: { alt: 'Host at the entrance', tone: 'ink', plate: 'PLATE 029' },
    tags: ['front of house'],
    status: 'ongoing',
  },
  {
    id: 'resident-selector',
    number: 47,
    category: 'person',
    title: 'The Resident Selector',
    description: 'Plays the room, not a setlist. Has never once repeated a Tuesday.',
    image: { alt: 'DJ behind the tape deck', tone: 'smoke', plate: 'PLATE 047' },
    tags: ['musician', 'resident'],
    status: 'ongoing',
  },
  {
    id: 'the-counter-maker',
    number: 12,
    category: 'person',
    title: 'The One Who Built the Counter',
    description: 'A furniture maker from Kampung Morten. The brass inlay was his idea, not the brief.',
    image: { alt: 'Maker working on the bar counter', tone: 'tobacco', plate: 'PLATE 012' },
    tags: ['maker', 'local'],
    status: 'archived',
  },
  {
    id: 'the-brass-jigger',
    number: 16,
    category: 'object',
    title: 'The Brass Jigger',
    description: 'Worn smooth by hand. Older than most of what it measures.',
    image: { alt: 'Worn brass jigger on the bar', tone: 'tobacco', plate: 'PLATE 016' },
    tags: ['bar tools'],
    status: 'ongoing',
  },
  {
    id: 'vinyl-no-114',
    number: 52,
    category: 'object',
    title: 'Vinyl No. 114',
    description: 'One record from the rotation, catalogued the way everything else here is catalogued.',
    image: { alt: 'Vinyl record sleeve, catalogued', tone: 'paper', plate: 'PLATE 052' },
    tags: ['music', 'object'],
    status: 'archived',
  },
  {
    id: 'the-first-opening',
    number: 9,
    category: 'night',
    title: 'The First Opening',
    description: 'The night the door opened for the first time. Kept, imperfectly, the way it happened.',
    date: '2025',
    image: { alt: 'Opening night at ARKIB', tone: 'ink', plate: 'PLATE 009' },
    tags: ['opening night'],
    status: 'archived',
  },
  {
    id: 'glassware-made-in-melaka',
    number: 44,
    category: 'collaboration',
    title: 'Glassware, Made in Melaka',
    description: 'A small run of glassware, thrown and fired by a local maker. Some pieces did not survive service.',
    image: { alt: 'Handmade glassware detail', tone: 'tobacco', plate: 'PLATE 044' },
    tags: ['local maker', 'glassware'],
    status: 'archived',
  },
  {
    id: 'the-river-at-night',
    number: 3,
    category: 'melaka',
    title: 'The River at Night',
    description: 'Two minutes’ walk from the door. The city ARKIB is a part of, not a backdrop for.',
    image: { alt: 'Melaka river at night', tone: 'smoke', plate: 'PLATE 003' },
    tags: ['melaka'],
    status: 'ongoing',
  },
]

export function getArchiveByCategory(category?: string): ArchiveEntry[] {
  const sorted = [...ARCHIVE].sort((a, b) => a.number - b.number)
  if (!category || category === 'all') return sorted
  return sorted.filter((entry) => entry.category === category)
}

export function getFeaturedDrinks(): DrinkEntry[] {
  return DRINKS.filter((d) => d.featured)
}

export const PEOPLE = ARCHIVE.filter((e) => e.category === 'person')
